### ISSUE TITLE
new function

### ISSUE THREAD

**Issue by PommesPeter** [neet-cv/LowLight-Metricsor#1]
make this repo as a pypi package, and we can just install this package to evaluate image metrics

**Comment by BreezeShane** [comment]
I used to try it but failed... It would be finished when I have a nice day...

**Comment by hanna-xu** [comment]
No such file or directory: '.../models/niqe_image_params.mat'

**Comment by PommesPeter** [comment]
> No such file or directory: '.../models/niqe_image_params.mat'

you can get it from https://github.com/guptapraful/niqe
